config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/team', to: 'static_pages#team'

  get '/contact', to: 'static_pages#contact'
  
  get '/welcome/:id', to: 'static_pages#welcome_user'

  post '/', to: 'static_pages#welcome_id', as: 'welcome'
  
  get '/gossip/:gossip_id', to: 'static_pages#gossip_id', as: 'gossip'

  get '/user/:user_id', to: 'static_pages#user_id', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :email, 
    presence: true,
    uniqueness: true,
    length: {in: 6..20}
  validates :content, presence: true
  belongs_to :user
  belongs_to :tag, optional: true
  has_many :likes
  has_many :comments, as: :comment_type
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city, optional: true
  has_many :gossips
  has_many :likes
  has_many :comments, as: :comment_type
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @gossips = Gossip.all
  end

  def welcome_user
    @gossips = Gossip.all
  end

  def gossip_id
    @gossip = Gossip.find(params["gossip_id"])
    @user = User.all #find(@gossip.user_id)
  end

  def user_id
    @user = User.find(params["user_id"])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

   <title>TheGossipProject</title>
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>

   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <header class="d-flex justify-content-center py-3">
      <ul class="nav nav-pills">
        <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link active"%></li>
        <li class="nav-item"><%= link_to "Team", team_path, class: "nav-link"%></li>
        <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link"%></li>
      </ul>
    </header>

 </head>

 <body>
   <%= yield %>


 </body>

</html>

app/views/static_pages/contact.html.erb
<h1>Nous contactes pas stp</h1>
<h2>On en a pas envie</h2>
<h3>Non, vraiment..</h3>
<h4>On reçoit trop de potins !</h4>
<h5>Mais si vraiment t'insistes...</h5>
<h6>email@gossip-project.com</h6>

app/views/static_pages/gossip_id.html.erb
<h1>Hello , voici le gossip numéro <%= params["gossip_id"] %>  ! </h1>

<p>
Son titre: <%= @gossip.title %> <br/>
Son auteur : <%= link_to @gossip.user.first_name, user_path(@gossip.user.id) %> <br/>
Son contenu : <%= @gossip.content %> <br/>
Créé le :<%= @gossip.created_at%>
</p>

app/views/static_pages/home.html.erb
<html>
  <body class= bg-light>
    <header>
        <div class="px-4 py-5 my-5 text-center">
          <h1 class="display-5 fw-bold">Bienvenue sur GOSSIP</h1>
            <div class="col-lg-6 mx-auto">
              <p class="lead mb-4">est-ce que tu veux des potins ?</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        </div>
    </header>

    <main class="container card-group">
      <% @gossips.each do |gossip| %> 
                  

        <div class="row row-cols-1 row-cols-md-2 g-4">
          <div class="col">
            <div class="card m-3 bg-white text-dark" style="width: 18rem;">
              <img src="https://img.pngio.com/gossip-podcast-gossip-png-500_500.png" class="card-img-top" alt="...">
              <div class="card-body text-center">
                <h5 class="card-title text-muted small">Gossip numéro <%= gossip.id%></h5>
                <p class="card-text ">Son titre: <%= gossip.title%></p>
                <p class="card-text text-primary small"> Son auteur : <%= gossip.user.first_name%> </p>
                <%= link_to "Lire son contenu", gossip_path(gossip), class:"btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
        
      <% end %>
    </main>

  </body>

</html>

app/views/static_pages/team.html.erb
<body class="text-center">
<h1> Hello, nous c'est Thomas et Baptiste, et c'est nous la team Gossip Project</h1>

<div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Baptiste</h2>
        <p>Blablabla j'en suis à la 6ème semaine de THP et je préfère le back.</p>
      </div>
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Thomas</h2>
        <p>Ca tombe bien, j'ai toujours préféré le front !</p>
      </div>

    </div>

</body>

app/views/static_pages/user_id.html.erb
<h1>Hello, voici notre auteur de potins numéro <%= params["user_id"] %>  ! </h1>

<p>
Son prénom: <%= @user.first_name %> <br/>
Son nom de famille: <%= @user.last_name %> <br/>
Sa ville : <%= @user.city.name %> <br/>
Son âge : <%= @user.age %> <br/>
Son email : <%= @user.email %> <br/>
</p>

app/views/static_pages/welcome_user.html.erb
<h1>Hello <%= params[:id] %> ! </h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>

<p>Pour accéder à tous les potins publiés, clique sur le bouton "Home" en haut !"</p>